// Generated by CoffeeScript 1.6.3
(function() {
  var cantonese;

  cantonese = require('../lingua-han-cantonese');

  exports.cantonese_test = {
    success: function(test) {
      test.expect(2);
      test.equals(cantonese.get('我') === 'ngo5', true);
      cantonese.setToneOff();
      test.equals(cantonese.get('我') === 'ngo', true);
      return test.done();
    }
  };

}).call(this);
